#!/usr/bin/env python3

from pathlib import Path
import runpy

runpy.run_path(str(Path(__file__).parent / "bootstrap_venvstarter.py"))

manager = __import__("venvstarter").manager("noy_pylama")
manager.add_pypi_deps(
    "pylama-dmypy==0.3", "mypy==0.950", "pylama==8.3.8", "noseOfYeti==2.3.1", "pyflakes==2.4.0"
)
manager.add_local_dep(
    "{here}",
    "..",
    version_file=(
        "strcs",
        "version.py",
    ),
    name="strcs=={version}",
    with_tests=True,
)
manager.min_python("3.10")
manager.run()
